name: CI
on:
  pull_request:
  workflow_dispatch:
  push:
    tags:
      - "*"
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-posters:
    name: "Build posters"
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Set up Python 3.10"
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: "Install dependencies"
        run: |
          python -m pip install -r requirements/requirements_doc.txt

      - name: "Install LaTeX packages"
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            texlive-base \
            texlive-latex-base \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            texlive-latex-recommended \
            texlive-latex-extra \
            texlive-science

      - name: "Install ghostscript"
        run: sudo apt install ghostscript

      - name: "Change ImageMagick security policy"
        run: |
          DQT='"'
          SRC="rights=${DQT}none${DQT} pattern=${DQT}PDF${DQT}"
          RPL="rights=${DQT}read|write${DQT} pattern=${DQT}PDF${DQT}"
          sudo sed -i "s/$SRC/$RPL/" /etc/ImageMagick-6/policy.xml

      - name: "Build posters"
        run: make all

      - name: "Upload posters"
        uses: actions/upload-artifact@v3
        with:
          name: posters
          path: out/*.pdf
